version: 2
references:
  set_var_pr: &set_var_pr
    run:
      name: set variable if PR
      command: |
        if [[ ! -z "${CIRCLE_PULL_REQUEST}" ]]; then
          echo "export HOLY_GRAIL=pr" >> $BASH_ENV
          echo "Is a PR"
        else
          echo "Not a PR"
        fi

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - *set_var_pr
      - run:
          name: Print the Current Time
          command: date
