version: 2
jobs:
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run: git tag v${CIRCLE_SHA1}
workflows:
  version: 2
  build_and_test:
    jobs:
      - test