
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:b4:7b:4b:23:07:cc:a5:62:00:de:f1:93:19:43:f7"
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git

      - run:
          name: Git add keys
          command: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - run:
          name: Greeting
          command: git tag v1.1

      - run:
          name: Git push tags
          command: git push --tags

      - run:
          name: Print the Current Time
          command: date